#!/bin/bash
# Update Packages
apt-get update -y
apt-get upgrade -y

# Set up Desktop Environment
apt-get install gnome-shell -y
apt-get install ubuntu-gnome-desktop -y
apt-get install autocutsel -y
apt-get install gnome-core -y
apt-get install gnome-panel -y
apt-get install gnome-themes-standard -y

# Install PPA/Git
add-apt-repository ppa:git-core/ppa
apt update -y
apt install git -y

# Set up VNC Server
apt-get install tightvncserver -y
touch ~/.Xresources

# Set Environment Variables - Senzing GH repo
export GIT_ACCOUNT=senzing
export GIT_REPOSITORY=docker-compose-demo
export GIT_ACCOUNT_DIR=~/${GIT_ACCOUNT}.git
export GIT_REPOSITORY_DIR="${GIT_ACCOUNT_DIR}/${GIT_REPOSITORY}"
export GIT_REPOSITORY_URL="https://github.com/${GIT_ACCOUNT}/${GIT_REPOSITORY}.git"

# Install Docker
apt install docker.io -y

# Install Docker Compose
curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose

# Clone senzing GH repo
mkdir --parents ${GIT_ACCOUNT_DIR}
cd  ${GIT_ACCOUNT_DIR}
git clone  --recurse-submodules ${GIT_REPOSITORY_URL}

# Set Environment Variables - Docker/host directories
export SENZING_DATA_DIR=${SENZING_VOLUME}/data
export SENZING_DATA_VERSION_DIR=${SENZING_DATA_DIR}/2.0.0
export SENZING_ETC_DIR=${SENZING_VOLUME}/etc
export SENZING_G2_DIR=${SENZING_VOLUME}/g2
export SENZING_VAR_DIR=${SENZING_VOLUME}/var
export POSTGRES_DIR=${SENZING_VAR_DIR}/postgres
export RABBITMQ_DIR=${SENZING_VAR_DIR}/rabbitmq

# Create directory for RabbitMQ Persistence
mkdir -p ${RABBITMQ_DIR}
chmod 770 ${RABBITMQ_DIR}

# Set Environment Variables - Accept Senzing EULA
export SENZING_ACCEPT_EULA="I_ACCEPT_THE_SENZING_EULA"

# Install Senzing
\
  --preserve-env \
  docker-compose --file ~/senzing.git/docker-compose-demo/resources/senzing/docker-compose-senzing-installation.yaml up
# Install RabbitMQ-Postgres Senzing Infra
\
  --preserve-env \
  docker-compose --file ~/senzing.git/docker-compose-demo/resources/postgresql/docker-compose-rabbitmq-postgresql.yaml up
